# Databricks notebook source
# MAGIC %sql
# MAGIC SELECT * FROM G_ELSEVIER_AFFILIATION

# COMMAND ----------

# MAGIC %sql
# MAGIC 
# MAGIC CREATE TABLE IF NOT EXISTS G_ELSEVIER_AFFILIATION_SECTOR
# MAGIC (
# MAGIC AFFILIATION_ID int,
# MAGIC SECTOR_ID int
# MAGIC );

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS G_SECTOR(
# MAGIC SECTOR_ID int,
# MAGIC SECTOR_LBL string,
# MAGIC SECTOR_DESC string
# MAGIC );

# COMMAND ----------

# MAGIC %sql
# MAGIC TRUNCATE TABLE G_SECTOR;

# COMMAND ----------

# MAGIC %sql
# MAGIC INSERT INTO G_SECTOR
# MAGIC values(1,'CFS','');
# MAGIC 
# MAGIC INSERT INTO G_SECTOR
# MAGIC values(2,'LMS','');
# MAGIC 
# MAGIC INSERT INTO G_SECTOR
# MAGIC values(3,'TBD','');

# COMMAND ----------

# MAGIC %sql
# MAGIC 
# MAGIC TRUNCATE TABLE G_ELSEVIER_AFFILIATION_SECTOR;
# MAGIC 
# MAGIC INSERT INTO G_ELSEVIER_AFFILIATION_SECTOR (
# MAGIC SELECT AFFILIATION_ID,1 FROM G_ELSEVIER_AFFILIATION WHERE UPPER(AFFILIATION_NM) like '%FOREST%' );
# MAGIC 
# MAGIC INSERT INTO G_ELSEVIER_AFFILIATION_SECTOR (
# MAGIC SELECT AFFILIATION_ID,2 FROM G_ELSEVIER_AFFILIATION WHERE UPPER(AFFILIATION_NM) like '%LAND%' );
# MAGIC 
# MAGIC 
# MAGIC INSERT INTO G_ELSEVIER_AFFILIATION_SECTOR (
# MAGIC SELECT AFFILIATION_ID,3 FROM G_ELSEVIER_AFFILIATION WHERE AFFILIATION_ID NOT IN (SELECT AFFILIATION_ID FROM G_ELSEVIER_AFFILIATION_SECTOR));

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT a.SECTOR_ID,SECTOR_LBL,COUNT(*) AS AFFIFILIATION_CNT FROM G_ELSEVIER_AFFILIATION_SECTOR a 
# MAGIC INNER JOIN G_SECTOR b 
# MAGIC   ON a.SECTOR_ID = b.SECTOR_ID
# MAGIC GROUP BY a.SECTOR_ID,b.SECTOR_LBL